#version: '3.9' 

services:
  go-app:
    container_name: go-app
    build:
      context: ..
      dockerfile: deployments/dockerfile
    environment:
      #DATABASE_URL: "host = go_db user=postgres password=postgres dbname=postgres sslmode=disable"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
    #volumes:
    #  - ..:/app
  go_db:
    container_name: go_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../scripts/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
  go_testdb:
    container_name: go_testdb
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: testpostgres
      POSTGRES_USER: testpostgres
      POSTGRES_DB: testpostgres
    ports:
      - "5432:5432"
    volumes:
      - ../scripts/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata: {}
