#use official go golang image
FROM golang:1.24.4

#set the working directory to /app
WORKDIR /app

#copy source files
COPY . .

#download and install the dependencies
RUN go get -v ./...

#build the go app
RUN GOOS=linux GOARCH=amd64 go build -o GoHttpRequestTaskProxy
RUN chmod +x GoHttpRequestTaskProxy
#expose the port
EXPOSE 8080

#run the executable
CMD ["./GoHttpRequestTaskProxy"]
