#version: '3.9' #obsolete according to https://dev.to/ajeetraina/do-we-still-use-version-in-compose-3inp

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "host = go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
